server:
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://124.70.222.113:3306/epcm_db #url
    username: root  #用户名
    password: wkx647667  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    connect-timeout: 300ms
    timeout: 1000ms
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 1000m

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1



mybatis:
  mapper-locations:
    classpath: mapper/*.xml
  type-aliases-package: com.epcm.entity
  configuration:
    map-underscore-to-camel-case: true
